# **Part 2: Pandas Basics, Useful Methods & Missing Data**

### **Dataset Introduction**

In this project, we will work with the Palmer Penguins dataset, which contains measurements of penguins observed on islands near Antarctica.

Please download the dataset [penguins.csv](https://drive.google.com/file/d/1dv8A8v_sdf29p1At40S7KBslJPmBA3e9/view?usp=sharing) or from canvas.

### **Dataset Description**

Each row represents a penguin, and columns include:

- species – Penguin species
- island – Island where the penguin was found
- bill_length_mm – Bill length (mm)
- bill_depth_mm – Bill depth (mm)
- flipper_length_mm – Flipper length (mm)
- body_mass_g – Body mass (grams)
- sex – Sex of the penguin

Some values are missing, which makes this dataset ideal for practicing missing data handling.

### **Load the Dataset**

In [2]:
import pandas as pd
df=pd.read_csv("penguins.csv")
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE

### **Part 1 — Basic Pandas Commands**

Q1. Display the last 5 rows of the dataset.

In [3]:
df.tail()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [4]:
# DO NOT RUN THIS

Q2. Answer the following, provide the code as well:

- How many rows and columns does the dataset have?

- What are the column names?

In [5]:
df.shape
#344 rows, 7 columns

(344, 7)

In [6]:
# DO NOT RUN THIS

In [7]:
df.columns
#names of the 7 columns:
#1species
#2island
#3bill length (millimeters)
#4bill depth (millimeters)
#5flipper length (millimeters)
#6body mass (grams)
#7sex

Index(['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex'],
      dtype='object')

In [8]:
# DO NOT RUN THIS

Q3. Use a single Pandas command to view:

- Data types
- Non-null counts

Are there any missing values?

In [9]:
df.info()
#there are 2 missing values of bill length, depth, flipper length, and body mass
#there are 20 missing values for sex.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                334 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

In [10]:
# DO NOT RUN THIS

Q4. Generate basic summary statistics for numerical columns.

In [11]:
df.describe()

       bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
count      342.000000     342.000000         342.000000   342.000000
mean        43.921930      17.151170         200.915205  4201.754386
std          5.459584       1.974793          14.061714   801.954536
min         32.100000      13.100000         172.000000  2700.000000
25%         39.225000      15.600000         190.000000  3550.000000
50%         44.450000      17.300000         197.000000  4050.000000
75%         48.500000      18.700000         213.000000  4750.000000
max         59.600000      21.500000         231.000000  6300.000000

In [12]:
# DO NOT RUN THIS

### **Part 2 — Selecting, Filtering & Sorting**

Q5. Select only the following columns:

- species
- island
- body_mass_g

In [13]:
df[['species','island','body_mass_g']]

    species     island  body_mass_g
0    Adelie  Torgersen       3750.0
1    Adelie  Torgersen       3800.0
2    Adelie  Torgersen       3250.0
3    Adelie  Torgersen          NaN
4    Adelie  Torgersen       3450.0
..      ...        ...          ...
339  Gentoo     Biscoe          NaN
340  Gentoo     Biscoe       4850.0
341  Gentoo     Biscoe       5750.0
342  Gentoo     Biscoe       5200.0
343  Gentoo     Biscoe       5400.0

[344 rows x 3 columns]

In [14]:
# DO NOT RUN THIS

Q6. Select all penguins that are on the island "Biscoe"

In [15]:
df[df['island'] == 'Biscoe']

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
20,Adelie,Biscoe,37.8,18.3,174.0,3400.0,FEMALE
21,Adelie,Biscoe,37.7,18.7,180.0,3600.0,MALE
22,Adelie,Biscoe,35.9,19.2,189.0,3800.0,FEMALE
23,Adelie,Biscoe,38.2,18.1,185.0,3950.0,MALE
24,Adelie,Biscoe,38.8,17.2,180.0,3800.0,MALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [16]:
# DO NOT RUN THIS

Q7. Select all penguins whose body_mass_g is greater than 5000

In [17]:
df[df['body_mass_g'] > 5000]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
221,Gentoo,Biscoe,50.0,16.3,230.0,5700.0,MALE
223,Gentoo,Biscoe,50.0,15.2,218.0,5700.0,MALE
224,Gentoo,Biscoe,47.6,14.5,215.0,5400.0,MALE
227,Gentoo,Biscoe,46.7,15.3,219.0,5200.0,MALE
229,Gentoo,Biscoe,46.8,15.4,215.0,5150.0,MALE
...,...,...,...,...,...,...,...
335,Gentoo,Biscoe,55.1,16.0,230.0,5850.0,MALE
337,Gentoo,Biscoe,48.8,16.2,222.0,6000.0,MALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [18]:
# DO NOT RUN THIS

Q8. Sort the dataset by bill_length_mm in descending order.
Do penguins with longer bills tend to appear heavier?

In [19]:
df_sorted = df.sort_values(by='bill_length_mm', ascending=False)
df_sorted

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
253,Gentoo,Biscoe,59.6,17.0,230.0,6050.0,MALE
169,Chinstrap,Dream,58.0,17.8,181.0,3700.0,FEMALE
321,Gentoo,Biscoe,55.9,17.0,228.0,5600.0,MALE
215,Chinstrap,Dream,55.8,19.8,207.0,4000.0,MALE
335,Gentoo,Biscoe,55.1,16.0,230.0,5850.0,MALE
...,...,...,...,...,...,...,...
70,Adelie,Torgersen,33.5,19.0,190.0,3600.0,FEMALE
98,Adelie,Dream,33.1,16.1,178.0,2900.0,FEMALE
142,Adelie,Dream,32.1,15.5,188.0,3050.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN

In [20]:
# DO NOT RUN THIS

### **Part 3 — Pandas Useful Methods**

Q9. How many penguins belong to each species?

Which species is the most common?

In [21]:
df['species'].value_counts().to_frame()

           count
species
Adelie       152
Gentoo       124
Chinstrap     68

In [22]:
# DO NOT RUN THIS

Q10. Find all unique islands present in the dataset.

In [23]:
df['island'].unique()

array(['Torgersen', 'Biscoe', 'Dream'], dtype=object)

In [24]:
# DO NOT RUN THIS

Q11. How many unique values are there in the sex column?

Does this number include missing values?

In [25]:
df['sex'].nunique()

3

In [26]:
# DO NOT RUN THIS

Q12. Identify the penguin with the largest flipper length.
Display the full row.

In [27]:
df.loc[df['flipper_length_mm'].idxmax()]

species              Gentoo
island               Biscoe
bill_length_mm         54.3
bill_depth_mm          15.7
flipper_length_mm     231.0
body_mass_g          5650.0
sex                    MALE
Name: 283, dtype: object

In [28]:
# DO NOT RUN THIS

Q13. Find the index of the penguin with the smallest body mass.
What is that penguin’s species?

In [29]:
smallest_mass = df['body_mass_g'].idxmin()
df.loc[smallest_mass, 'species']

'Chinstrap'

In [30]:
# DO NOT RUN THIS

Q14. Find the 5 penguins with the smallest flipper length.

In [41]:
df.nsmallest(5, 'flipper_length_mm')

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
28,Adelie,Biscoe,37.9,18.6,172.0,3150.0,FEMALE
20,Adelie,Biscoe,37.8,18.3,174.0,3400.0,FEMALE
122,Adelie,Torgersen,40.2,17.0,176.0,3450.0,FEMALE
30,Adelie,Dream,39.5,16.7,178.0,3250.0,FEMALE
31,Adelie,Dream,37.2,18.1,178.0,3900.0,MALE

In [31]:
# DO NOT RUN THIS

Q15. Filter penguins whose flipper_length_mm is between 180 and 210 mm.

In [43]:
df[df['flipper_length_mm'].between(180,210)].reset_index(drop=True)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
4,Adelie,Torgersen,39.3,20.6,190.0,3650.0,MALE
...,...,...,...,...,...,...,...
229,Gentoo,Biscoe,47.5,14.2,209.0,4600.0,FEMALE
230,Gentoo,Biscoe,48.4,14.4,203.0,4625.0,FEMALE
231,Gentoo,Biscoe,41.7,14.7,210.0,4700.0,FEMALE
232,Gentoo,Biscoe,43.3,14.0,208.0,4575.0,FEMALE
233,Gentoo,Biscoe,48.1,15.1,209.0,5500.0,MALE

In [32]:
# DO NOT RUN THIS

Q16. Check whether the dataset contains any duplicate rows.

In [44]:
df.duplicated().sum()

np.int64(0)

In [33]:
# DO NOT RUN THIS

Q17. Replace "MALE" and "FEMALE" with lowercase values.

In [46]:
df['sex'] = df['sex'].str.lower()

In [49]:
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female

Q18. Create species_code:

- Adelie → 1
- Chinstrap → 2
- Gentoo → 3

In [50]:
df['species_code'] = df['species'].map({'Adelie': 1, 'Chinstrap': 2, 'Gentoo': 3})

In [34]:
# DO NOT RUN THIS
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE

Q19. Create `bill_ratio = bill_length / bill_depth`.

In [52]:
df['bill_ratio'] = df['bill_length_mm'] / df['bill_depth_mm']

In [53]:
df['bill_ratio']

0      2.090909
1      2.270115
2      2.238889
3           NaN
4      1.901554
         ...
339         NaN
340    3.272727
341    3.210191
342    3.054054
343    3.099379
Name: bill_ratio, Length: 344, dtype: float64

In [35]:
# DO NOT RUN THIS
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE

Q20. Which variable is most strongly correlated with body_mass_g?

In [54]:
df.corr(numeric_only=True)['body_mass_g'].sort_values(ascending=False)
#body_mass will obviously be 1, as its trends are being compared with itself
#flipper length is most strongly correlated.

body_mass_g          1.000000
flipper_length_mm    0.871202
species_code         0.750491
bill_ratio           0.703119
bill_length_mm       0.595110
bill_depth_mm       -0.471916
Name: body_mass_g, dtype: float64

In [36]:
# DO NOT RUN THIS

### **Part 4 — Missing Data**

Q21. Identify how many missing values exist in each column.

In [55]:
df.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  10
species_code          0
bill_ratio            2
dtype: int64

In [37]:
# DO NOT RUN THIS

Q22. Select all rows where:

- body_mass_g is missing
- species is known

In [56]:
df[df['body_mass_g'].isnull() & df['species'].notnull()]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_code,bill_ratio
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,1,NaN
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,3,NaN

In [38]:
# DO NOT RUN THIS

Q23. Keep only rows that have at least 5 non-missing values.

In [57]:
df_filtered = df.dropna(thresh=5)

In [39]:
# DO NOT RUN THIS

Q24. Replace missing values in the sex column with "Unknown".

In [59]:
df['sex'] = df['sex'].fillna("Unknown")
df['sex']

0         male
1       female
2       female
3      Unknown
4       female
        ...
339    Unknown
340     female
341       male
342     female
343       male
Name: sex, Length: 344, dtype: object

Q25. Fill missing values in body_mass_g using the mean of that column.

In [60]:
df['body_mass_g'] = df['body_mass_g'].fillna(df['body_mass_g'].mean())

In [40]:
# DO NOT RUN THIS

df['body_mass_g'].mean() computes the average body mass, and .fillna() assigns that average value to all missing entries in body_mass_g.